version: '3.9'
services:
  db:
    image: mysql:8.0.31
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysqlDB:/var/lib/mysql
  wordpress:
    image: wordpress:6.0.2
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
volumes:
  wordpress:
  mysqlDB: