version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - ./database/wordpress_data:/var/lib/mysql
